eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://daxzg83339dns.eastus2.cloudapp.azure.com:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
